console.log("Hello");
console.log("Hello");
try{
    console.log(a);
}
catch(error_caught){
    console.log("Error caught by catch block");
    console.log(error_caught);
}
console.log("Hello2");
console.log("Hello2");